---
title: "MANOJ KUMAR - 2048015"
author: "CAC-2"
date: "19/03/2021"
output: word_document
---

```{r warning=FALSE}
suppressMessages(library(tidyverse))        # Data manipulation and plots
suppressMessages(library(funModeling))      # Overview stats
library(magrittr)                           # To use pipes
library(skimr)                              # To get a quick summary table
library(caret)                              # To create the partition for training/test datasets

options(scipen = 999)                       # Turn off scientific notation for numbers
options(repr.plot.width=12, 
        repr.plot.height=8)                 # Set universal plot size
```


```{r}
# Reading the dataset
df          <- read.csv('insurance.csv')

# Denote factor variables
df$sex      <- factor(df$sex)
df$smoker   <- factor(df$smoker)
df$region   <- factor(df$region)
df$children <- factor(df$children)
```


```{r}
# check for missing values
df %>%
    is.na() %>%
    sum()
```


```{r}
# check data types
df %>%
    str()
```


```{r}
skim(df)
```

```{r}
figsize <- options(repr.plot.width=18, repr.plot.height=18) # set plot size for this plot 

# Smoker count plot
smoker <- df %>%
    ggplot(aes(x=smoker, fill=smoker)) +
    geom_bar(show.legend = FALSE) +
    geom_text( stat='count',
        aes(label=paste0(round(after_stat(prop*100), digits=1), "%"),group=1),
        vjust=-0.4, size=4 ) +
    labs(  x = "", y = "", title = "Number of policyholders by smoking"  ) +
    scale_x_discrete( labels = c("no" = "Non-smoker", "yes" = "Smoker")  ) +
    scale_y_continuous( breaks=seq(0,2000,100) ) +
    theme(
        plot.title = element_text(size=16),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14)
    )
```


```{r}
# Region count plot
region <- df %>%
    ggplot(aes(x=forcats::fct_infreq(region), fill=region)) +
    geom_bar(show.legend = FALSE) +
    geom_text( stat='count', 
               aes(label = paste0(round(after_stat(prop*100), digits=1), "%"), group=1), 
               vjust=-0.4, size=4 ) +
    labs( x = "", y = "", title = "Number of policyholders by region"  ) +
    scale_x_discrete( labels = c("northeast" = "North East", "northwest" = "North West",
                   "southeast" = "South East", "southwest" = "South West") ) +
    scale_y_continuous( breaks=seq(0,350,50) ) +
    theme(
        plot.title = element_text(size=16),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14)
    )
```


```{r}
# Sex count plot
sex <- df %>%
    ggplot(aes(x=forcats::fct_infreq(sex), fill=sex)) +
    geom_bar(show.legend = FALSE) +
    geom_text(stat='count',
        aes( label=paste0(round(after_stat(prop*100), digits=1), "%"), group=1),
        vjust=-0.4, size=4 ) +
    labs( x = "",  y = "", title = "Number of policyholders by sex", fill = "Sex" ) +
    scale_x_discrete(  labels = c("male" = "Male", "female" = "Female")  ) +
    scale_y_continuous(  breaks=seq(0,700,100) ) +
    theme(
        plot.title = element_text(size=16),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14)
    )
```


```{r}
# Children count plot
children <- df %>%
    ggplot(aes(x=forcats::fct_infreq(children), fill=children)) +
    geom_bar(show.legend = FALSE) +
    geom_text(stat='count',
        aes(label=paste0(round(after_stat(prop*100), digits=1), "%"), group=1),
        vjust=-0.4, size=4 ) +
    labs( x = "", y = "", title = "Number of dependents per policy" ) +
    scale_x_discrete( labels = c("0" = "None") ) +
    scale_y_continuous( breaks=seq(0,600,50) ) +
    theme(
        plot.title = element_text(size=16),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14)
    )
```


```{r}
# Plot grid
cowplot::plot_grid( smoker, region, sex, children, labels="AUTO", ncol = 2, nrow = 2 )
options(figsize)
```


```{r}
figsize <- options(repr.plot.width=20, repr.plot.height=16)

# Age distribution
age_hist <- df %>%
    ggplot(aes(x=age))+
    geom_histogram( binwidth = 5, show.legend = FALSE, fill="#ff5733" )+
    labs( x = "Ages of policyholders",  y = "Number of policyholders",
        title = "Distribution of ages" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

age_dens <- df %>%
    ggplot(aes(x=age)) + geom_density( alpha=.3, fill="#ff5733" )+
    labs( x = "Ages of policyholders", y = "Probability density",
        title = "Distribution of ages" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

age_box <- df %>%
    ggplot(aes(y=age)) +
    geom_boxplot( alpha=.5, fill="#ff5733" )+
    coord_flip() +
    theme(
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    )+
    labs( y = "Ages of policyholders", x = "", title = "Distribution of ages" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
# BMI distribution
bmi_hist <- df %>%
    ggplot(aes(x=bmi))+
    geom_histogram(binwidth = 4, show.legend = FALSE, fill = "#55ab11" )+
    labs( x = "BMI scores of policyholders", y = "Number of policyholders",
        title = "Distribution of BMI scores" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_dens <- df %>%
    ggplot(aes(x=bmi)) + geom_density(  alpha=.3, fill="#55ab11" )+
    labs(
        x = "BMI scores of policyholders",
        y = "Probability density",
        title = "Distribution of BMI scores" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_box <- df %>%
    ggplot(aes(y=bmi)) +
    geom_boxplot( alpha=.5, fill="#55ab11" )+
    coord_flip() +
    theme( axis.text.y = element_blank(),
        axis.ticks.y = element_blank() )+
    labs( y = "BMI scores of policyholders", x = "",
        title = "Distribution of BMI scores" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
# Charges distribution
charges_hist <- df %>%
    ggplot(aes(x=charges)) +
    geom_histogram(  binwidth = 2000, show.legend = FALSE, fill = "#FFC300" )+
    labs( x = "Charges to policyholders ($)", y = "Number of policyholders",
        title = "Distribution of medical charges" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

charges_dens <- df %>%
    ggplot( aes(x=charges) ) +
     geom_density( alpha=.3, fill="#FFC300" ) +
    labs( x = "Charges to policyholders ($)", y = "Probability density",
        title = "Distribution of medical charges" ) +
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

charges_box <- df %>%
    ggplot(aes(y=charges))+
    geom_boxplot( alpha=.5, fill="#FFC300" )+ coord_flip()+
    theme( axis.text.y = element_blank(), axis.ticks.y = element_blank() )+
    labs( y = "Charges to policyholders ($)", x = "",
        title = "Distribution of medical charges" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
cowplot::plot_grid( age_hist, age_dens, age_box, bmi_hist, bmi_dens, bmi_box,
    charges_hist, charges_dens, charges_box, labels="AUTO", ncol = 3, nrow = 3 )

options(figsize)
```


```{r}
figsize <- options(repr.plot.width=20, repr.plot.height=26)

# Boxplots
chargesBysmoker <- df %>%
    ggplot( aes( x=forcats::fct_reorder(smoker, charges, .fun=median, .desc=TRUE),
            y=charges, fill=smoker  ) ) +
    geom_boxplot(show.legend = FALSE) +
    coord_flip() +
    labs(  x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges by smoking" )+
    scale_x_discrete(
        labels = c("no" = "Non-smoker", "yes" = "Smoker") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

chargesByregion <- df %>%
    ggplot( aes( x=forcats::fct_reorder(region, charges, .fun=median, .desc=TRUE),
            y=charges,  fill=region  ) ) +
    geom_boxplot(show.legend = FALSE) +
    coord_flip() +
    labs( x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges by region" )+
    scale_x_discrete( labels = c("northeast" = "North East", "northwest" = "North West",
                    "southeast" = "South East", "southwest" = "South West") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

chargesBychildren <- df %>%
    ggplot( aes(  x=forcats::fct_reorder(children, charges, .fun=median, .desc=TRUE),
            y=charges, fill=children ) ) +
    geom_boxplot(show.legend = FALSE) + coord_flip() +
    labs(  x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges by dependents" )+
    scale_x_discrete(  labels = c("0" = "None") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

chargesBysex <- df %>%
    ggplot(
    aes( x=forcats::fct_reorder(sex, charges, .fun=median, .desc=TRUE),
        y=charges,  fill=sex  ) ) +
    geom_boxplot(show.legend = FALSE) +
    coord_flip() +
    labs(  x = "", y = "Charges to policyholders ($)",  
           title = "Distribution of charges by sex" )+
    scale_x_discrete( labels = c("male" = "Male", "female" = "Female") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
# Density plots with medians
densityBySmoker <- df %>%
    ggplot( aes( x=forcats::fct_reorder(smoker, charges, .fun=median, .desc=TRUE),
            y=charges, fill=smoker ) ) +
    geom_violin(show.legend = FALSE) +
    geom_boxplot( width=0.1, show.legend = FALSE )+ coord_flip() +
    labs( x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges with density by smoking"
    )+ scale_x_discrete( labels = c("no" = "Non-smoker", "yes" = "Smoker") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

densityByRegion <- df %>%
    ggplot( aes( x=forcats::fct_reorder(region, charges, .fun=median, .desc=TRUE),
            y=charges, fill=region ) ) +
    geom_violin(show.legend = FALSE) +
    geom_boxplot(
        width=0.1,
        show.legend = FALSE
    )+    coord_flip() +
    labs( x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges with density by region" )+
    scale_x_discrete(labels = c("northeast" = "North East", "northwest" = "North West",
                                "southeast" = "South East", "southwest" = "South West") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

densityBySex <- df %>%
    ggplot(
    aes( x=forcats::fct_reorder(sex, charges, .fun=median, .desc=TRUE),
        y=charges,  fill=sex  ) ) +
    geom_violin(show.legend = FALSE) +
    geom_boxplot(  width=0.1, show.legend = FALSE )+    coord_flip() +
    labs( x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges with density by sex" )+
    scale_x_discrete( labels = c("male" = "Male", "female" = "Female") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

densityByChildren <- df %>%
    ggplot( aes( x=forcats::fct_reorder(children, charges, .fun=median, .desc=TRUE),
            y=charges, fill=children ) ) +
    geom_violin(show.legend = FALSE) +
    geom_boxplot( width=0.1, show.legend = FALSE )+    coord_flip() +
    labs(  x = "", y = "Charges to policyholders ($)",
        title = "Distribution of charges with density by dependents")+
    scale_x_discrete( labels = c("0" = "None") )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
# Plot grid of all plots
cowplot::plot_grid(
    chargesBysmoker, densityBySmoker,
    chargesByregion, densityByRegion,
    chargesBysex, densityBySex,
    chargesBychildren, densityByChildren,
    labels="AUTO", ncol = 2, nrow = 4
)

options(figsize)
```


```{r}
figsize <- options(repr.plot.width=12, repr.plot.height=8)

age_scatter <- df %>%
    ggplot(aes(x=age, y=charges)) + geom_point()+ geom_smooth(method='lm')+
    labs( x = "Ages of policyholders",y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder Age" )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_scatter <- df %>%
    ggplot(aes(x=bmi, y=charges)) +
    geom_point()+
    geom_smooth(method='lm')+
    labs( x = "BMI scores of policyholders", y = "Charges to policyholders ($)", 
          title = "Medical Charges vs Policyholder BMI" )+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
cowplot::plot_grid( age_scatter, bmi_scatter, labels="AUTO", ncol = 2, nrow = 1 )

options(figsize)
```


```{r}
figsize <- options(repr.plot.width=20, repr.plot.height=22)

# by sex
age_scatter_sex <- df %>%
    ggplot(aes(x=age, y=charges, color=sex)) +
    geom_point()+
    labs( x = "Ages of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder Age by Sex", color = "Sex:" )+
    scale_color_hue(labels = c("male" = "Male", "female" = "Female"))+ guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_scatter_sex <- df %>%
    ggplot(aes(x=bmi, y=charges, color=sex)) + geom_point()+
    labs( x = "BMI scores of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder BMI by Sex", color = "Sex:" )+
    scale_color_hue(labels = c("male" = "Male", "female" = "Female"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
#by smoker
age_scatter_smoker <- df %>%
    ggplot(aes(x=age, y=charges, color=smoker)) +
    geom_point()+
    labs( x = "Ages of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder Age by Smoking", color = "Smoker:" )+
    scale_color_hue(labels = c("no" = "Non-smoker", "yes" = "Smoker"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_scatter_smoker <- df %>%
    ggplot(aes(x=bmi, y=charges, color=smoker)) +
    geom_point()+
    labs(  x = "BMI scores of policyholders",  y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder BMI by Smoking",
        color = "Smoking:" )+
    scale_color_hue(labels = c("no" = "Non-smoker", "yes" = "Smoker"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
#by children
age_scatter_kids <- df %>%
    ggplot(aes(x=age, y=charges, color=children)) +
    geom_point()+
    labs(  x = "Ages of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder Age by Dependents",
        color = "Dependents:" )+
    scale_color_hue(labels = c("no" = "Non-smoker", "yes" = "Smoker"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
bmi_scatter_kids <- df %>%
    ggplot(aes(x=bmi, y=charges, color=children)) +
    geom_point()+
    labs( x = "BMI scores of policyholders",  y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder BMI by Dependents",
        color = "Dependents:" )+
    scale_color_hue(labels = c("0" = "None"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
#by region
age_scatter_region <- df %>%
    ggplot(aes(x=age, y=charges, color=region)) +
    geom_point()+
    labs( x = "Ages of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder Age by Region", color = "Regions:" )+
    scale_color_hue(labels = c("northeast" = "North East", "northwest" = "North West",
                                "southeast" = "South East", "southwest" = "South West"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

bmi_scatter_region <- df %>%
    ggplot(aes(x=bmi, y=charges, color=region)) +
    geom_point()+
    labs( x = "BMI scores of policyholders", y = "Charges to policyholders ($)",
        title = "Medical Charges vs Policyholder BMI by Regions", color = "Regions:" )+
    scale_color_hue(labels = c("northeast" = "North East", "northwest" = "North West",
                                "southeast" = "South East", "southwest" = "South West"))+
    guides(fill=FALSE)+
    theme(
        plot.title = element_text(size=18),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
# make a grid
cowplot::plot_grid(
    age_scatter_sex, bmi_scatter_sex,
    age_scatter_smoker, bmi_scatter_smoker,
    age_scatter_kids, bmi_scatter_kids,
    age_scatter_region, bmi_scatter_region,
    labels="AUTO", ncol = 2, nrow = 4 )

options(figsize)
```

## Multiple linear regression

```{r}
charges_hist <- df %>%
    ggplot( aes(x=charges) ) +
    geom_histogram( binwidth = 2000, show.legend = FALSE, fill = "#FFC300" )+
    labs( x = "Charges to policyholders ($)", y = "Number of policyholders",
        title = "Distribution of medical charges" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )

charges_hist_log10 <- df %>%
    ggplot( aes(x=log10(charges))  ) +
    geom_histogram( show.legend = FALSE, fill = "#FFC300" )+
    labs( x = "Charges to policyholders log10 transformed",
        y = "Number of policyholders", title = "Distribution of medical charges after log10 transform" )+
    theme(
        plot.title = element_text(size=16),
        axis.text = element_text(size=14),
        axis.title = element_text(size=14)
    )
```


```{r}
cowplot::plot_grid( charges_hist, charges_hist_log10, labels="AUTO", ncol = 2, nrow = 1 )
```

## Split the dataset and train the model

```{r}
# log10 transform of response variable 
df$logCharges<- log10(df$charges)

drops <- c("charges")
df[ , !(names(df) %in% drops)]

# Split the data into training and test sets
set.seed(122)                    # Set the seed to make the partition reproducible
training.samples <- df$logCharges %>%
  createDataPartition(p = 0.8, list = FALSE)

train  <- df[training.samples, ]
test <- df[-training.samples, ]
```


### Modelling

```{r}
library(ridge) 
library(e1071)
library(ggplot2)
library(rpart)
library(rpart.plot)
```


##  Multi Linear Regression

```{r}
# Fitting Multiple Linear Regression to the Training set
formula <- as.formula("logCharges ~ smoker + bmi + age + children + sex + region")
model <- lm(formula, data = train)

summary(model)
```

### Evaluating the model

```{r}
# Make predictions on the training dataset
predictions <- model %>% predict(train)
# Calculating the residuals
residuals <- train$logCharges - predictions
# Calculating Root Mean Squared Error
rmse <- sqrt(mean(residuals^2))

rmse %>%
    round(digits=3)
```

```{r}
predictions <- model %>% predict(test)
residuals <- test$logCharges - predictions
rmse <- sqrt(mean(residuals^2))

rmse %>%
    round(digits=3)
```

```{r}
# Calculating RMSE for training data with backtransformed data
predictions <- model %>% predict(train)
residuals <- 10^train$logCharges - 10^predictions # backtransform measured and predicted values
rmse <- sqrt(mean(residuals^2))
round(rmse)
```

```{r}
# Calculating RMSE for testing data with backtransformed data
predictions <- model %>% predict(test)
residuals <- 10^test$logCharges - 10^predictions # backtransform measured and predicted values
rmse <- sqrt(mean(residuals^2))
round(rmse)
```

### Linear Ridge

```{r}
linRidgeMod = linearRidge(logCharges ~ ., data = train)
predicted = predict(linRidgeMod, test) 
compare1 = cbind (actual=test$logCharges, predicted)

mean (apply(compare1, 1, min)/apply(compare1, 1, max))
RMSE = sqrt(mean((test$logCharges-predicted)^2))
RMSE

# summary
summary(linRidgeMod)
```

### SVR 

```{r}
regressor = svm(formula = logCharges ~ age, data = df, type = 'eps-regression', kernel = 'radial')
y_pred = predict(regressor, data.frame(age = 37))

# Visualizing the SVR results
ggplot() + geom_point(aes(x = df$age, y = df$logCharges), colour = 'red') +
  geom_line(aes(x = df$age, y = predict(regressor, newdata = df)), colour = 'blue') +
  ggtitle('Truth or Bluff (SVR)') + xlab('age') + ylab('logCharges')
```

### Decision Tree Regression 

```{r}
regressor = rpart(formula = logCharges ~ age, data = df, control = rpart.control(minsplit = 1))
y_pred = predict(regressor, data.frame(age = 37))

ggplot() + geom_point(aes(x = df$age, y = df$logCharges), colour = 'red') +
  geom_line(aes(x = df$age, y = predict(regressor, newdata = df)), colour = 'blue') +
  ggtitle('Truth or Bluff (Decision Tree Regression)') + xlab('age') + ylab('logCharges')
```

### Tree plot

```{r}
tree = rpart(logCharges ~ smoker + bmi + age + children + sex + region, data=df)
prp(tree)
```

## Random Forest 

```{r}
myControl = trainControl(method = "cv", number = 5, verboseIter = FALSE)
model_rf = train(logCharges ~ smoker + bmi + age + children + sex + region, data = train,
              tuneLength = 1, method = "ranger", importance = 'impurity',
              trControl = myControl)
model_rf
```



